### ISSUE TITLE
Blink before next page fades in

### ISSUE THREAD

**Issue by edinabazi** [blivesta/animsition#27]
Whenever I click on a link with the 'linkElement' class in it, the previous page that's supposed to fade out blinks for a second after fading out then the next page starts to fade in. It looks pretty bad. Is there a known fix for this?

**Comment by gauravpadia** [comment]
Hello @edinabazi 

Check your body styles. Is there any other animation properties applied ? like animation duration, animation name, animation timings etc. other than this animsition styles ?

**Comment by edinabazi** [comment]
Nope. [This](http://img7.yehpic.com/f1fc28ff49ff94532f2a69fe346629da.png) is what I have applied to the body. I also tried removing "position: relative;", no luck.

**Comment by gauravpadia** [comment]
Would you please check the styles on div that you have added animistion class ? I mean check if there is any animation properties applied other than animistion class ? 

If possible please share website URL.

Thanks.

**Comment by edinabazi** [comment]
I've created a new div with a completely new class so there aren't any other styles applied to it. [http://abazi.mk/argjiratest](Here)'s the URL of the site I'm working on.

**Comment by gauravpadia** [comment]
Ok I saw. The issue is you have used "fade" class in div element. You should use "animsition" class because in animsition.css the required initial style properties are applied in "animsition" class. 

After changing class of course you will also need to change class name in your argjira.js.

Other way is you change class name to fade in animsition.css.

I think it should fix your issue. I hope this makes sense.

Thanks.

**Comment by edinabazi** [comment]
Changing the .animsition class in animsition.css to .fade worked! Thank you so much!
